import java.util.ArrayList;
import java.util.Random;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {


    public static ArrayList<Integer> roll(int n) {
        Random randomRoll = new Random();
        int rolledDie = randomRoll.nextInt(6) + 1;
        ArrayList<Integer> rollResultArray = new ArrayList<Integer>();

        for (int i = 0; i < n; i++) {        System.out.println(rollResultArray + "test message");

            rollResultArray.add(rolledDie);
        }
    return rollResultArray;
    }
}
