import java.util.*;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {


    public static void main(String[] args){
        System.out.println(Arrays.toString(roll(10)));
    }

    public static int [] roll(int n) {

        int[] rollResultArray = new int[n];
        Random randomRoll = new Random();

        for (int i = 0; i < n; i++) {
            int rolledDie = randomRoll.nextInt(6) + 1;
            rollResultArray[i] = rolledDie;
        }
    return rollResultArray;
    }



    public static boolean containsDuplicates(String[] inputArray){
       boolean duplicates = false;

        for (int i = 0; i < inputArray.length; i++){
            for (int j = i + 1; j < inputArray.length; j++){
                if (j != i && inputArray[j] == inputArray[i])
                    duplicates = true;
            }

        }
        return duplicates;
    }

    public static double calculateAverageOfArray(int[] inputArray){
        int aggregate = 0;

        for (int i = 0; i < inputArray.length; i++){
            aggregate += inputArray[i];
        }

        double average = (double) aggregate / inputArray.length;
        return average;

    }

}
