/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.*;
import static org.junit.Assert.*;

public class LibraryTest {



    @Test public void testRollMethod() {
        int expected = 3;
        int result = Library.roll(3).size();
        System.out.println(result+ "test message");

        assertEquals(expected, result);

    }
    @Test public void testDuplicatesMethod() {

        String[]testArrayOne = {"1","2","3"};
        String[]testArrayTwo = {"1","2","3"};
        assertTrue("The arrays should return true", Library.containsDuplicates(testArrayOne, testArrayTwo));

    }

    }


