/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import java.util.*;

import static org.junit.Assert.*;

public class LibraryTest {

    @Test public void testRollMethod() {
        int expected = 10;

        // test return arrays are the same in length
        assertEquals("Returned array should be equal to expected", expected, Library.roll(expected).length);
        // test return arrays return different values
        assertNotEquals("Returned array should not be the same", Arrays.toString(Library.roll(expected)), Arrays.toString(Library.roll(expected)));

    }
    @Test public void testDuplicatesMethod() {

        String[]testArrayOne = {"1","2","3", "4", "5"};
        String[]testArrayTwo = {"1","2","3", "3"};

        assertFalse("The arrays should return false", Library.containsDuplicates(testArrayOne));
        assertTrue("The array should return true", Library.containsDuplicates(testArrayTwo));

    }

    @Test public void testAverageOfArray() {

        int[] testArrayOne = {1,2,3,4,5};
        double expected = 15 / 5;


        assertEquals(expected, Library.calculateAverageOfArray(testArrayOne), 0);

    }

    @Test public void testLowestAverageArray() {

        int[][] weeklyMonthTemperatures = {
                {1, 2, 3, 4, 5, 6, 7},
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
        };
        int [] expected =  {1, 2, 3, 4, 5, 6, 7};


        assertArrayEquals(expected, Library.lowestAverageArray(weeklyMonthTemperatures));

    }

    /**
     * Assertion tests for method Library.getMissingElement
     * Assertion tests for method Library.getMinValue
     * Assertion tests for method Library.getMaxValue
     */
    @Test public void testGetMaxMinAbsentValues() {
        int[][] test2DArray = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57},
        };

        List<String> testArrayList = new ArrayList<>();
        testArrayList.add("High: 72");
        testArrayList.add("Low: 51");
        testArrayList.add("Never saw temperature: 63");
        testArrayList.add("Never saw temperature: 67");
        testArrayList.add("Never saw temperature: 68");
        testArrayList.add("Never saw temperature: 69");

        assertEquals("Array lists should be the same", testArrayList, Library.getUniqueValue(test2DArray));
    }

    @Test public void testGetMaxValue() {


        int[][] weeklyMonthTemperatures = {
                {1, 2, 3, 4, 5, 6, 7},
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
        };
        int expected = 72;

        HashSet<Integer> missingElement = Library.getMissingElement(weeklyMonthTemperatures);
        int maxValue = Library.getMaxValue(missingElement);


        assertEquals("return value should be equal to expected", expected, maxValue);

    }

    @Test public void testGetMinValue() {

        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
        };
        int expected = 51;

        HashSet<Integer> missingElement = Library.getMissingElement(weeklyMonthTemperatures);
        int minValue = Library.getMinValue(missingElement);


        assertEquals("return value should be equal to expected", expected, minValue);

    }

    @Test public void testGetMissingValue() {

        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };


        List<String> testArrayList = new ArrayList<>();
        testArrayList.add("Never saw temperature: 63");
        testArrayList.add("Never saw temperature: 67");
        testArrayList.add("Never saw temperature: 68");
        testArrayList.add("Never saw temperature: 69");

        assertEquals("Array lists should be the same", testArrayList, Library.getUniqueValue(weeklyMonthTemperatures));

    }

    @Test public void testTally() {
        List<String> votes = new ArrayList<>();
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");

        String expectedResult = "Bush received the most votes!";

        assertEquals("Strings should be the same", expectedResult, Library.tally(votes));
    }







}


