import java.util.LinkedList;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Restaurant {
    private String name;
    private int numberOfStars;
    private String priceCategory;
    protected LinkedList<Review> reviewsList;


    public Restaurant(String name, int numberOfStars, String priceCategory) {
        this.name = name;
        this.numberOfStars = numberOfStars;
        this.priceCategory = priceCategory;
        this.reviewsList = new LinkedList();

    }

    public String getName() {
        return name;
    }

    public int getNumberOfStars() {
        return this.numberOfStars;
    }

    public String getPriceCategory() {
        return this.priceCategory;
    }

    public String toString() {
        String restaurantRating;
        if (numberOfStars < 0) {
            restaurantRating = "restaurant hasn't been rated yet";
        }else{
                restaurantRating = String.valueOf((this.numberOfStars));
            }

            String str = "Name: " + this.name + " Number of Stars: " + restaurantRating
                    + " Price Category: " + this.priceCategory;
            for (Review review : reviewsList) {
                str += review.toString();
            }
            return str;
        }

        public void addReview (Review review){
            reviewsList.add(review);

        }



    }




