/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Restaurant {
    private String name;
    private int numberOfStars;
    private String priceCategory;

    public Restaurant(String name, int numberOfStars, String priceCategory){
        this.name = name;
        this.numberOfStars = numberOfStars;
        this.priceCategory = priceCategory;
    }

    public String getName(){
        return name;}

    public int getNumberOfStars(){
        return this.numberOfStars;
    }

    public String getPriceCategory(){
        return this.priceCategory;
    }

    public String toStringRestaurant(){
        String str = "Name: " + this.name + " Number of Stars: " +this.numberOfStars + " Price Category: " + this.priceCategory;
        return str;
    }







    public boolean someLibraryMethod() {
        return true;
    }
}
