import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Restaurant {
    private String name;
    private int numberOfStars;
    private String priceCategory;
    protected LinkedList<Review> reviewsList;
    protected List<Integer> starRatings;



    public Restaurant(String name, String priceCategory) {
        this.name = name;
        this.numberOfStars = -1;
        this.priceCategory = priceCategory;
        this.reviewsList = new LinkedList();
        this.starRatings = new ArrayList<>();


    }

    public String getName() {
        return name;
    }

    public int getNumberOfStars() {
        return this.numberOfStars;
    }

    public String getPriceCategory() {
        return this.priceCategory;
    }

    public String toString() {
        String restaurantRating;
        if (numberOfStars < 0) {
            restaurantRating = "No ratings yet ";
        }else{
                restaurantRating = String.valueOf((this.numberOfStars));
            }

            String str = "\nName: " + this.name + "\nNumber of Stars: " + restaurantRating
                    + "\nPrice Category: " + this.priceCategory;
            for (Review review : reviewsList) {
                str += review.toString();
            }
            return str;
        }


        public void addReview (Review review){
            reviewsList.add(review);
            updateStars(review);
        }


    public void updateStars(Review stars) {
        this.starRatings.add(stars.getStars());
        Integer total = 0;
        for (Integer star : starRatings) {
            total += star;
        }
        this.numberOfStars = total / starRatings.size();
    }


    }




