/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import java.nio.file.FileSystems;
import java.nio.file.Path;
import java.nio.file.Paths;

import static org.junit.Assert.*;

public class LinterTest {
    @Test public void linterTestEmptyFile() {
        Path testFile = FileSystems.getDefault().getPath("resources/empty.js");
        assertEquals("Should return 0", 0, Linter.semicolonLinter(testFile));
        
    }
}
