/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class RestaurantTest {
    @Test public void testGetName() {
        Restaurant r = new Restaurant("Skippy's", "$$$");

        assertEquals("Skippy's", r.getName());
    }


    /**
     * Restaurant Class - toString() method test
     */

    @Test public void testToStringRestaurant() {
        Restaurant r = new Restaurant("Skippy's", "$$$");

        assertEquals("\nName: " + r.getName() + "\nNumber of Stars: No ratings yet " + "\nPrice Category: " + r.getPriceCategory(),r.toString());
    }

    @Test public void testToStringRestaurant2() {
        Restaurant r = new Restaurant("Subway", "$$");

        assertEquals("\nName: " + r.getName() + "\nNumber of Stars: No ratings yet " + "\nPrice Category: " + r.getPriceCategory(),r.toString());
    }
    @Test public void testToStringRestaurant3() {
        Restaurant r = new Restaurant("McDonald's", "$$");

        assertEquals("\nName: " + r.getName() + "\nNumber of Stars: No ratings yet " + "\nPrice Category: " + r.getPriceCategory(),r.toString());
    }

    /**
     * test Review Class for toString method
     *
     */


    @Test public void testToStringEmptyBodyReview() {
        Review r = new Review("", "Steve",5);

        assertEquals("Body: " + r.getBody() + " Author: " + r.getAuthor()+ " Stars: " + r.getStars(),r.toString());
    }
    @Test public void testToStringReviewEmptyAuthor() {
        Review r = new Review("only ok", "",5);

        assertEquals("Body: " + r.getBody() + " Author: " + r.getAuthor()+ " Stars: " + r.getStars(),r.toString());
    }
    @Test public void testToStringReview() {
        Review r = new Review("only ok", "Steve",5);

        assertEquals("Body: " + r.getBody() + " Author: " + r.getAuthor()+ " Stars: " + r.getStars(),r.toString());
    }

    /**
     * Add Review test for class Review
     *
     */
    @Test public void testAddReview() {
        Restaurant r = new Restaurant("Chili's","$$");

        r.addReview(new Review("meh", "Mr.Meh", 2));
        assertEquals( 1, r.reviewsList.size());

        r.addReview(new Review("meh2", "Mr.Meh2", 2));
        assertEquals( 2, r.reviewsList.size());

        r.addReview(new Review("meh3", "Mr.Meh", 3));
        assertEquals( 3, r.reviewsList.size());

    }


    /**
     * update stars rating 
     */
    @Test public void testUpdateStars() {
        Restaurant r = new Restaurant("Chili's","$$");

        r.addReview(new Review("meh", "Mr.Meh", 4));

        r.addReview(new Review("meh2", "Mr.Meh2", 2));
        assertEquals( 3, r.getNumberOfStars());
        r.addReview(new Review("meh3", "Mr.Meh3", 1));
        assertEquals( 2, r.getNumberOfStars());
        r.addReview(new Review("meh4", "Mr.Meh4", 5));
        assertEquals( 3, r.getNumberOfStars());


    }






}
