/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class RestaurantTest {
    @Test public void testSomeLibraryMethod() {
        Restaurant classUnderTest = new Restaurant();
            System.out.println(classUnderTest.toString());
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
