import java.io.BufferedReader;
import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;


/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Linter {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        Path fileToLinter = FileSystems.getDefault().getPath("resources/gates.js");
        semicolonLinter(fileToLinter);
    }

    public static void semicolonLinter(Path fileToLinter){

        Charset charset = Charset.forName("US-ASCII");
        try{
            BufferedReader reader = Files.newBufferedReader(fileToLinter, charset);
            String nextLine;

            int lineNumber = 0;

            while((nextLine = reader.readLine()) != null){
                lineNumber++;
                if(!nextLine.isEmpty()
                    && !nextLine.endsWith("{")
                    && !nextLine.endsWith("}")
                    && !nextLine.contains("if")
                    && !nextLine.contains("else")){
                    System.out.println("Line " + lineNumber + ": Missing semicolon.");
                }

            }

        }
        catch(IOException e){
            System.out.println(e);
        }







    }


}
