import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;


/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Linter {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        Path fileToLinter = FileSystems.getDefault().getPath("resources/gates.js");
        semicolonLinter(fileToLinter);
    }

    public static int semicolonLinter(Path fileToLinter){
        int errorCount = 0;

        try{
            BufferedReader reader = Files.newBufferedReader(fileToLinter);
            String nextLine = "";

            int lineNumber = 0;


            while(nextLine != null) {
                    if (!nextLine.isEmpty()
                            && !nextLine.endsWith("{")
                            && !nextLine.endsWith("}")
                            && !nextLine.contains("if")
                            && !nextLine.contains("else")
                            && !nextLine.endsWith(";")) {
                        System.out.println("Line " + lineNumber + ": Missing semicolon.");
                        errorCount++;

                    }
                    nextLine = reader.readLine();
                    lineNumber++;
                }


        }

        catch(IOException e){

        }


        return errorCount;
    }


}
